name: Code Quality Check

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    branches:
      - main  # Trigger the workflow for pull requests targeting the main branch

jobs:
  lint:
    runs-on: ubuntu-latest  # The job will run on an Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # This step checks out the repository's code

      - name: Set up Python
        uses: actions/setup-python@v4  # This sets up Python in the environment
        with:
          python-version: '3.9'  # Specify the Python version to use

      - name: Install dependencies
        run: |
          pip install black flake8  # Install Black for code formatting and Flake8 for linting

      - name: Run Black
        run: black --check .  # Check if the code is properly formatted according to Black's rules

      - name: Run Flake8
        run: flake8 .  # Lint the code using Flake8 to catch any issues or violations
